feat(blog): tenant or namespaces, pick at least one
bsctl/clastix.io pull request #2
Opened 2021-12-31 10:20 UTC by prometherion

![screencapture-localhost-8000-blog-multi-tenancy-options-for-kubernetes-tenant-or-namespaces-pick-at-least-one-html-2021-12-31-11_19_02](https://user-images.githubusercontent.com/9697646/147817826-5f79f47a-062c-4e13-a440-7bbb6a0f21f5.png)

2021-12-31 11:57 UTC, bsctl requested changes
LGTM, pls just resolve the comments and then merge.

2021-12-31 11:57 UTC, bsctl commented on docs/blog/index.html
> +                With the accelerating adoption of <strong>Kubernetes</strong>strong> the dilemma of multi-tenancy is gaining more traction and being more hot and relevant. Implementing a multi-tenanc
<strong>Kubernetes</strong>

2021-12-31 11:57 UTC, bsctl commented on docs/blog/index.html
> +                Tenant, or Namespaces…? Pick at least one!
please, remove dots ... from the title

`Multi-tenancy options for Kubernetes: Tenant, or Namespaces? Pick at least one!`

2021-12-31 13:53 UTC, prometherion commented on docs/blog/index.html
> +                With the accelerating adoption of <strong>Kubernetes</strong>strong> the dilemma of multi-tenancy is gaining more traction and being more hot and relevant. Implementing a multi-tenanc
I don't get this comment, my bad.

2021-12-31 15:40 UTC, bsctl commented on docs/blog/index.html
> +                With the accelerating adoption of <strong>Kubernetes</strong>strong> the dilemma of multi-tenancy is gaining more traction and being more hot and relevant. Implementing a multi-tenanc
There is a strong one more time <strong>Kubernetes</strong>strong>

2022-01-01 16:56 UTC, bsctl approved these changes

2022-01-01 16:56 UTC, merged